### ISSUE TITLE
prepare_train_set.sh not running because of "xv_task"

### ISSUE THREAD

**Issue by AnfengXu136** [BUTSpeechFIT/DVBx#1]
We are getting an error from line 31 of prepare_train_set.sh: bash $xvec_dir/xv_task.
The error is "xvec_dir/xv_task: not such file or directory."
It seems like xv_task is never created. Do you have a solution for this?

**Comment by domklement** [comment]
Hi,

I've just cloned the repo and it worked. 

I did the following:
```
git clone git@github.com:BUTSpeechFIT/DVBx.git
cd DVBx
conda env create -f conda_env.yml
mkdir exp_dir
mkdir exp_dir/xvec_dir
./prepare_train_set.sh "xvectors" "./exp_dir/" "./exp_dir/xvec_dir/"
```

Also, you need to update the dataset paths:
```
WAV_DIR= # wav files directory
FILE_LIST= # txt list of files to process
LAB_DIR= # lab files directory with VAD segments
REF_DIR= # reference rttm files directory
```

I'll update the readme with this info and describe the paths in more details. Sorry for that.

Can you please describe the details of your setup and how you tried to run the script? It will help us to identify the issue.

Also, I've just fixed a minor code issue. Please, pull the changes.

Best,
Dominik

**Comment by AnfengXu136** [comment]
It is running now, thank you for getting back to me.
I updated the dataset paths accordingly and ran similar commands previously, but maybe I missed something.

**Comment by domklement** [comment]
Awesome. Let us know if you need help with setting things up. Good Luck!
